export const siteConfig = {
  name: "Mohit Pandya",
  title: "Mohit Pandya | Full Stack Developer & AI Engineer",
  description:
    "Portfolio of Mohit Pandya, a full stack developer and AI engineer building polished web apps, backend systems, and intelligent products.",
  url: "https://portfolioo-five-drab.vercel.app",
  email: "mohitpandya808@gmail.com",
  phoneDisplay: "+91 92840 49090",
  phoneLink: "+919284049090",
  whatsappUrl: "https://wa.me/919284049090",
  githubUrl: "https://github.com/spixet",
  linkedinUrl: "https://linkedin.com/in/mohitpandya",
  twitterHandle: "@Spixet",
  twitterUrl: "https://x.com/Spixet",
  location: "Mumbai, Maharashtra, India",
  resumePath: "/resume.pdf",
  ogImagePath: "/og-image.svg",
  twitterImagePath: "/twitter-image.svg",
  profileImagePath: "/images/profile-photos/mohit-avatar.svg",
  keywords: [
    "Mohit Pandya",
    "Full Stack Developer",
    "AI Engineer",
    "Web Developer",
    "Next.js",
    "React",
    "Node.js",
    "TypeScript",
    "Portfolio",
    "Software Engineer",
  ],
} as const;
